apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eaglesoft-sync.configMapName" . }}
  labels:
    {{- include "eaglesoft-sync.labels" . | nindent 4 }}
data:
  sync_config.yaml: |
    {{- .Values.syncConfig | nindent 4 }}
